#!/bin/bash

# This is a sample DAEMON file which is started at boottime. 
# CAUTION! MAKE SURE YOUR SCRIPT EXITS CLEANLY! It is a good idea
# to start your daemon as background process. If you do something wrong here
# your user's systems may hang forever during boottime!

# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

shareavailable=`cat /etc/samba/smb.conf | grep plugindata | wc -l`

if [ $shareavailable = 0 ]
then
	# to ensure that Sonos can read from folder structure
	echo " " >> $LBHOMEDIR/system/samba/smb.conf
	echo "[plugindata]" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   comment = LoxBerry Plugin Data" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   path = $LBPDATA" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   guest ok = yes" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   read only = no" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   directory mask = 0700" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   create mask = 0700" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   follow symlinks = yes" >> $LBHOMEDIR/system/samba/smb.conf
	echo "   wide links = yes" >> $LBHOMEDIR/system/samba/smb.conf
	#echo "   Sonos plugin requires a reboot to enable the TTS share" >> $LBHOMEDIR/log/system_tmpfs/reboot.required
	# Restart Samba Server
	systemctl reload smbd.service
fi

exit 0
